### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by HudsonMota** [gustavodividino/scrummer-laravel#1]
bom dia amigo, poderia disponibilizar o login pré-definido ao sistema?
agradeço desde já

**Comment by gustavodividino** [comment]
Bom dia coleta,
dentro do seed, tem a criação de usuarios aleatorios que utilizamos para fazer a apresentação do TCC e tem o de administrador também: 
                'name' => 'Administrador',
                'surname' => 'Scrummer',
                'email' => 'administrador@empresa.com',
                'password' => bcrypt('123456'),

**Comment by gustavodividino** [comment]
> bom dia amigo, poderia disponibilizar o login pré-definido ao sistema?
> agradeço desde já

Bom dia coleta,
dentro do seed, tem a criação de usuarios aleatorios que utilizamos para fazer a apresentação do TCC e tem o de administrador também:
'name' => 'Administrador',
'surname' => 'Scrummer',
'email' => 'administrador@empresa.com',
'password' => bcrypt('123456'),

**Comment by HudsonMota** [comment]
Bom dia meu querido.
amigo, essa senha é => bcrypt('123456'), ou apenas 123456?
tentei das 2 formas e não consegui

Em ter., 22 de jun. de 2021 às 16:56, gustavodividino <
***@***.***> escreveu:

**Comment by gustavodividino** [comment]
Bom Dia colega!
Você precisa executar a criação das tabelas e fazer o seed depois para que os usuários sejam cadastrados no banco
php artisan migrate -> Cria as tabelas
php artisan db:seed -> Popula as tabelas

Com isso, os usuarios de Adm serão criados. a senha é 123456, o bycrpt é para criptografar a senha para salvar no banco de dados.
